# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='jobs',
  syntax='proto3',
  serialized_options=b'\n\026org.hopenly.ilyde.grpcB\rJobAgentProtoP\001\242\002\003JAS',
  serialized_pb=b'\n\x0b\x61gent.proto\x12\x04jobs\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x0fOperationStatus\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\rCommitRequest\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1f\n\x0bSyncRequest\x12\x10\n\x08revision\x18\x01 \x01(\t\"0\n\x0e\x43hangeResponse\x12\r\n\x05total\x18\x01 \x01(\r\x12\x0f\n\x07\x63hanges\x18\x02 \x03(\t2\xbd\x01\n\x10JobAgentServices\x12\x32\n\x04Sync\x12\x11.jobs.SyncRequest\x1a\x15.jobs.OperationStatus\"\x00\x12\x36\n\x06\x43ommit\x12\x13.jobs.CommitRequest\x1a\x15.jobs.OperationStatus\"\x00\x12=\n\ngetChanges\x12\x16.google.protobuf.Empty\x1a\x15.jobs.OperationStatus\"\x00\x42/\n\x16org.hopenly.ilyde.grpcB\rJobAgentProtoP\x01\xa2\x02\x03JASb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_OPERATIONSTATUS = _descriptor.Descriptor(
  name='OperationStatus',
  full_name='jobs.OperationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='jobs.OperationStatus.status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='jobs.OperationStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=100,
)


_COMMITREQUEST = _descriptor.Descriptor(
  name='CommitRequest',
  full_name='jobs.CommitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='jobs.CommitRequest.msg', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=130,
)


_SYNCREQUEST = _descriptor.Descriptor(
  name='SyncRequest',
  full_name='jobs.SyncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='revision', full_name='jobs.SyncRequest.revision', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=163,
)


_CHANGERESPONSE = _descriptor.Descriptor(
  name='ChangeResponse',
  full_name='jobs.ChangeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='jobs.ChangeResponse.total', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='changes', full_name='jobs.ChangeResponse.changes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['OperationStatus'] = _OPERATIONSTATUS
DESCRIPTOR.message_types_by_name['CommitRequest'] = _COMMITREQUEST
DESCRIPTOR.message_types_by_name['SyncRequest'] = _SYNCREQUEST
DESCRIPTOR.message_types_by_name['ChangeResponse'] = _CHANGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OperationStatus = _reflection.GeneratedProtocolMessageType('OperationStatus', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONSTATUS,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jobs.OperationStatus)
  })
_sym_db.RegisterMessage(OperationStatus)

CommitRequest = _reflection.GeneratedProtocolMessageType('CommitRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMITREQUEST,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jobs.CommitRequest)
  })
_sym_db.RegisterMessage(CommitRequest)

SyncRequest = _reflection.GeneratedProtocolMessageType('SyncRequest', (_message.Message,), {
  'DESCRIPTOR' : _SYNCREQUEST,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jobs.SyncRequest)
  })
_sym_db.RegisterMessage(SyncRequest)

ChangeResponse = _reflection.GeneratedProtocolMessageType('ChangeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHANGERESPONSE,
  '__module__' : 'agent_pb2'
  # @@protoc_insertion_point(class_scope:jobs.ChangeResponse)
  })
_sym_db.RegisterMessage(ChangeResponse)


DESCRIPTOR._options = None

_JOBAGENTSERVICES = _descriptor.ServiceDescriptor(
  name='JobAgentServices',
  full_name='jobs.JobAgentServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=216,
  serialized_end=405,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sync',
    full_name='jobs.JobAgentServices.Sync',
    index=0,
    containing_service=None,
    input_type=_SYNCREQUEST,
    output_type=_OPERATIONSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Commit',
    full_name='jobs.JobAgentServices.Commit',
    index=1,
    containing_service=None,
    input_type=_COMMITREQUEST,
    output_type=_OPERATIONSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getChanges',
    full_name='jobs.JobAgentServices.getChanges',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_OPERATIONSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOBAGENTSERVICES)

DESCRIPTOR.services_by_name['JobAgentServices'] = _JOBAGENTSERVICES

# @@protoc_insertion_point(module_scope)
